apiVersion : v1
kind : Pod
metadata:
  name: with-pod-affinity
  labels:
    name: with-pod-affinity

spec:
  containers:
  - name: with-pod-affinity
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity-1
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - with-pod-affinity
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: with-pod-affinity
    image: nginx
