apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    app: nginx
    demo: service
spec:
  containers:
    - name: nginx-nodeport
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx-nodeport
    demo: service
  ports:
    - protocol: TCP
      port: 80 # Service Port
      targetPort: 80 # container Port