apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - name: hello-pod
      image: nginx
      ports:
        - containerPort: 80
    - name: almalinux-container
      image: almalinux:8
      command: ["/bin/sh", "-c", "while true; do sleep 300; done"]
